/**
 * UnknownItemsService — 005 Wave 1 / T511 (CAPTURE-HAPPY).
 *
 * Owns the data-layer writes for the POS unknown-item capture path.
 * Wave 1 / CAPTURE-HAPPY scope is intentionally minimal: every POS
 * submission produces a fresh `pending` `unknown_items` row, full stop.
 *
 * Out of scope for THIS slice (each lands in a downstream Wave 1 slice
 * that EXTENDS this service):
 *   - Alias-resolution prelude (FR-022 / FR-030 / FR-031) →
 *       005-WAVE1-CAPTURE-RESOLVE (T513/T514)
 *   - Submitting-store scope on alias lookup (FR-030a) →
 *       005-WAVE1-CAPTURE-STORE-SCOPE (T515/T516)
 *   - Natural dedup of pending rows (FR-032) →
 *       005-WAVE1-CAPTURE-DEDUP (T517/T518)
 *   - Non-disclosing get-by-id (SI-004 / FR-013 / FR-092) →
 *       005-WAVE1-NON-DISCLOSING (T521/T522)
 *   - List + dismiss → 005-WAVE1-LIST / 005-WAVE1-DISMISS
 *   - Idempotency-mismatch audit + counter (FR-021c, FR-082) →
 *       005-WAVE1-IDEMP-MISMATCH (T533) — the existing
 *       `IdempotencyInterceptor` already provides the 409 outcome;
 *       this slice does not author the catalog-domain mismatch hook.
 *
 * Hard constraints (constitutional + plan-binding):
 *   - Every DB call runs inside `runWithTenantContext(...)` per 003 §8 +
 *     001 helpers. No raw pool access.
 *   - The store GUC `app.current_store` is set explicitly inside the
 *     transactional callback (003's RLS INSERT policy checks it).
 *   - No PII in logs: `value` is catalog reference data (per Constitution
 *     §XIV + 003 §10 redaction matrix) and is not redacted, but
 *     `sale_context` is opaque advisory JSON and MUST NOT be logged
 *     verbatim — pino redaction at the boundary takes care of this when
 *     a downstream slice wires a structured log statement. The current
 *     slice does not log `sale_context`.
 *
 * See:
 *   specs/005-pos-catalog-sync-reconciliation/spec.md §5 US1, §6.1–§6.4
 *   specs/005-pos-catalog-sync-reconciliation/data-model.md §2.1 + §2.2
 *   packages/contracts/openapi/catalog/unknown-items.yaml — posCaptureItem
 */
import { Inject, Injectable } from "@nestjs/common";
import type { Pool } from "pg";
import { randomUUID } from "node:crypto";

import { runWithTenantContext } from "@data-pulse-2/db";

import { PG_POOL } from "../../auth/auth.module";
import { recordUnknownItemCaptured } from "../../observability/metrics/api.metrics";

/**
 * Inputs accepted at the service boundary. Mirrors the contract's
 * `PosCaptureItemRequest` (Zod-validated upstream in the controller).
 * `tenantId`, `storeId`, and `actorUserId` come from the resolved POS
 * principal context — body-supplied tenant/store fields are NOT trusted
 * (Constitution §III).
 */
export interface CaptureItemInput {
  readonly tenantId: string;
  readonly storeId: string;
  /** POS principal's `userId` per `ResolvedContext` (= device identity). */
  readonly actorUserId: string;
  readonly correlationId: string;
  readonly identifierType: "barcode" | "sku" | "plu" | "supplier_code" | "external_pos_id";
  readonly identifierValue: string;
  readonly sourceSystem: string | null;
  readonly saleContext: Record<string, unknown> | null;
}

/**
 * Raw row shape returned by the INSERT ... RETURNING clause. Aligned to
 * the 003 `unknown_items` Drizzle schema; the controller adapts to the
 * contract `UnknownItem` shape.
 */
export interface CapturedUnknownItemRow {
  readonly id: string;
  readonly tenantId: string;
  readonly storeId: string;
  readonly identifierType: string;
  readonly identifierValue: string;
  readonly sourceSystem: string | null;
  readonly resolutionStatus: "pending";
  readonly resolutionAction: null;
  readonly resolvedAt: null;
  readonly resolvedBy: null;
  readonly resolvedProductId: null;
  readonly encounteredAt: Date;
  readonly saleContext: Record<string, unknown> | null;
}

/**
 * Discriminated-union return shape mirroring the contract's
 * `PosCaptureResolvedResponse | PosCaptureUnknownResponse`.
 * Wave 1 CAPTURE-HAPPY only emits the `unknown` variant; the `resolved`
 * variant lands in CAPTURE-RESOLVE (T514).
 */
export type CaptureItemResult = {
  readonly kind: "unknown";
  readonly unknownItem: CapturedUnknownItemRow;
};

@Injectable()
export class UnknownItemsService {
  constructor(@Inject(PG_POOL) private readonly pool: Pool) {}

  /**
   * Capture a POS-submitted item reference as a new `pending`
   * `unknown_items` row. Returns the persisted row.
   *
   * The transactional contract:
   *   - One row INSERTed inside `runWithTenantContext` (`app.current_tenant`
   *     set) with `app.current_store` set explicitly so the 003 INSERT
   *     policy `unknown_items_insert` passes.
   *   - `id` is a UUIDv4 generated by `crypto.randomUUID()`. (UUIDv7
   *     would be marginally better for index locality but 003's PK
   *     column is `uuid` without v7 enforcement; this matches the
   *     existing 005 fixture-helper pattern.)
   *   - `resolution_status` defaults to `'pending'` per 003 schema; we
   *     pass it explicitly for clarity. Resolution fields are NULL
   *     (enforced by `CHK unknown_items_resolved_fields_consistent`).
   *
   * Metric: `unknown_item_captured_total` is incremented after a
   * successful INSERT (no label cardinality).
   */
  async captureItem(input: CaptureItemInput): Promise<CaptureItemResult> {
    const id = randomUUID();

    const row = await runWithTenantContext(
      this.pool,
      { tenantId: input.tenantId, isPlatformAdmin: false },
      async (client) => {
        // 003's RLS INSERT policy on `unknown_items` checks the store GUC;
        // `runWithTenantContext` sets only the tenant + platform-admin
        // GUCs, so we set `app.current_store` inside the transaction.
        await client.query(
          "SELECT set_config('app.current_store', $1, true)",
          [input.storeId],
        );

        const result = await client.query<{
          id: string;
          tenant_id: string;
          store_id: string;
          identifier_type: string;
          value: string;
          source_system: string | null;
          resolution_status: "pending";
          resolution_action: null;
          resolved_at: null;
          resolved_by: null;
          resolved_product_id: null;
          encountered_at: Date;
          sale_context: Record<string, unknown> | null;
        }>(
          `INSERT INTO unknown_items
             (id, tenant_id, store_id, identifier_type, value,
              source_system, resolution_status, sale_context,
              correlation_id)
           VALUES
             ($1, $2, $3, $4, $5, $6, 'pending', $7, $8)
           RETURNING id, tenant_id, store_id, identifier_type, value,
                     source_system, resolution_status, resolution_action,
                     resolved_at, resolved_by, resolved_product_id,
                     encountered_at, sale_context`,
          [
            id,
            input.tenantId,
            input.storeId,
            input.identifierType,
            input.identifierValue,
            input.sourceSystem,
            input.saleContext,
            input.correlationId,
          ],
        );

        const r = result.rows[0];
        if (!r) {
          // RLS returning zero rows on a self-insert means the principal's
          // tenant/store context did not satisfy `unknown_items_insert`.
          // This is a guard error, not a domain error; surface a thrown
          // exception rather than corrupt the response shape.
          throw new Error("unknown_items: insert produced no row");
        }
        return r;
      },
    );

    recordUnknownItemCaptured();

    const captured: CapturedUnknownItemRow = {
      id: row.id,
      tenantId: row.tenant_id,
      storeId: row.store_id,
      identifierType: row.identifier_type,
      identifierValue: row.value,
      sourceSystem: row.source_system,
      resolutionStatus: "pending",
      resolutionAction: null,
      resolvedAt: null,
      resolvedBy: null,
      resolvedProductId: null,
      encounteredAt: row.encountered_at,
      saleContext: row.sale_context,
    };

    return { kind: "unknown", unknownItem: captured };
  }
}
