/**
 * `outbox_events` — durable transactional outbox table. (T570)
 *
 * Rows are written by producers inside the same DB transaction as the
 * business state change. The drainer worker polls, claims via
 * `FOR UPDATE SKIP LOCKED`, and hands rows to registered consumers.
 *
 * RLS-enabled by `tenant_id`. Every row is visible only to the tenant
 * that produced it (or to a platform admin). The drainer establishes
 * tenant context before any downstream DB access beyond reading or
 * updating the outbox row itself (Constitution §V, §II).
 *
 * Delivery states:
 *   pending      -> freshly inserted, not yet claimed
 *   claimed      -> drainer holds a lock; processing in flight
 *   delivered    -> consumer confirmed successful processing
 *   failed       -> consumer threw; eligible for retry (backoff in next_attempt_at)
 *   dead_lettered -> budget exhausted (8 attempts); awaiting operator triage
 *
 * First registered event type: `audit.event.created` (FR-C-007).
 * Additional event types require a separate approval PR per T541.
 */
import { integer, jsonb, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const outboxEvents = pgTable("outbox_events", {
  /**
   * Primary key. UUIDv7 preferred (time-ordered, aids index scans and
   * ordering); UUIDv4 fallback acceptable. Generated by the producer at
   * insert time. Also serves as the consumer dedup key.
   */
  eventId: uuid("event_id").primaryKey(),

  /**
   * Tenant scope. NOT NULL -- every outbox event belongs to exactly one
   * tenant. The RLS policy gates visibility on this column.
   */
  tenantId: uuid("tenant_id").notNull(),

  /**
   * Store scope. NULL for tenant-level events; populated for store-level
   * events.
   */
  storeId: uuid("store_id"),

  /**
   * Registry-controlled name. First allowed value: `audit.event.created`.
   * New event types require a separate approval PR (T541).
   */
  eventType: text("event_type").notNull(),

  /**
   * Event-type-specific body. Subject to redaction at the logger boundary
   * (Constitution XIV, FR-C-008). Never logged in full.
   */
  payload: jsonb("payload").notNull(),

  /**
   * Lifecycle state. Enforced by a CHECK constraint at the DB layer.
   * `claimed` is the in-flight state: a drainer holds a row-level lock.
   */
  deliveryState: text("delivery_state").notNull(),

  /**
   * Number of claim attempts so far. Incremented at claim time inside the
   * claim CTE (not in the failure handler). Budget is 8 (lifecycle.md section 4).
   */
  attempts: integer("attempts").notNull().default(0),

  /**
   * When the row becomes eligible for the next claim attempt. NULL means
   * immediately eligible (initial pending rows). Set by the drainer when
   * transitioning to `failed`, per the bounded exponential backoff schedule
   * (lifecycle.md section 4.2).
   */
  nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true }),

  /**
   * Redacted error class only -- never the full exception string, never PII,
   * never payload data. Set by the drainer on every transition to `failed`
   * or `dead_lettered`.
   */
  lastError: text("last_error"),

  /**
   * Business event timestamp (UTC). Distinct from `created_at` -- an event
   * may record a moment that occurred before it was written to the outbox.
   */
  occurredAt: timestamp("occurred_at", { withTimezone: true })
    .notNull()
    .defaultNow(),

  /**
   * Row insert time. Equals the producer's transaction commit time. Not
   * the same as `occurred_at` for events representing past moments.
   */
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),

  /**
   * Row last-modified time. Updated by the drainer on every state transition.
   */
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),

  /**
   * Set when the row transitions to `delivered` or `dead_lettered`.
   * NULL while the row is pending, claimed, or failed.
   */
  processedAt: timestamp("processed_at", { withTimezone: true }),

  /**
   * End-to-end trace / correlation identifier from the originating request
   * or worker job. Optional. Carries through consumer downstream calls for
   * structured-log correlation (FR-B-004).
   */
  correlationId: uuid("correlation_id"),
});

export type OutboxEventRow = typeof outboxEvents.$inferSelect;
export type NewOutboxEventRow = typeof outboxEvents.$inferInsert;
