/**
 * T232 — AuditFanoutProcessor spec.
 *
 * Pure unit-level: no Redis, no Postgres, no Testcontainers, no BullMQ runtime.
 * The processor is instantiated directly with a Jest-spy DbLike seam — the same
 * pattern used by EmailProcessor + RecordingEmailAdapter.
 *
 * Coverage follows the T232 approval list exactly:
 *   - happy path field mapping
 *   - malformed payload (MalformedAuditJobError → DLQ intent)
 *   - transient DB error propagation (→ BullMQ retry)
 *   - id generated by processor (not from payload, no DB default)
 *   - occurred_at absent from insert row (DB DEFAULT now() stamps it)
 *   - safe metadata stored as-is
 *   - top-level blocked key (token) → {}
 *   - nested blocked key (data.secret) → {}
 *   - null metadata → {}
 *   - non-object metadata (string) → {}
 *   - blocked key inside a nested array element → {}
 *   - non-plain object metadata (Date instance) → {}
 *   - nested non-plain object value (e.g. { when: new Date() }) → {}
 *   - deeply nested beyond depth cap → {} (fail closed)
 *   - valid UUID request_id forwarded
 *   - non-UUID request_id coerced to null
 *   - null request_id kept null
 *   - tenant_id UUID forwarded
 *   - tenant_id null forwarded (RLS guards at DB, not here)
 *   - unknown job name → UnknownAuditJobError
 *   - AUDIT_FANOUT_JOB_NAME literal pin
 *   - T303: jobs with traceContext still parse and insert normally
 *   - T303: active context inside process() carries the producer traceId
 */
// T596: mock the worker.metrics module BEFORE importing the processor. See
// the equivalent block in apps/worker/test/email/email.processor.spec.ts —
// same rationale (avoid OTel SDK at unit-test time, spy on call counts).
jest.mock("../../src/observability/metrics/worker.metrics", () => {
  const WORKER_ERROR_CLASSES = new Set([
    "TenantContextMissingError",
    "ZodValidationError",
    "PostgresUniqueViolation",
    "RedisConnectionError",
    "Timeout",
    "UnknownError",
  ]);
  return {
    recordWorkerJobDuration: jest.fn(),
    recordWorkerProcessingFailure: jest.fn(),
    sanitizeErrorClass: jest.fn((name: string | null | undefined) =>
      typeof name === "string" && WORKER_ERROR_CLASSES.has(name) ? name : "UnknownError",
    ),
  };
});

import {
  AuditFanoutProcessor,
  AUDIT_FANOUT_JOB_NAME,
  MalformedAuditJobError,
  UnknownAuditJobError,
  type AuditDbLike,
  type AuditEventInsertRow,
} from "../../src/audit/audit-fanout.processor";
import {
  createTestTracerProvider,
  context,
  trace,
  injectTraceContext,
  type TestTracerHandle,
} from "@data-pulse-2/shared/observability/otel";
import {
  recordWorkerJobDuration,
  recordWorkerProcessingFailure,
} from "../../src/observability/metrics/worker.metrics";

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const ACTOR_USER_ID  = "0a000000-0000-7000-8000-00000000aa01";
const TENANT_ID      = "0b000000-0000-7000-8000-0000000b1001";
const STORE_ID       = "0c000000-0000-7000-8000-0000000c5001";
const TARGET_ID      = "0d000000-0000-7000-8000-0000000d0001";
const REQUEST_ID_OK  = "018e4a1b-1234-7abc-8def-000000000001";

const VALID_PAYLOAD = {
  actor_user_id: ACTOR_USER_ID,
  actor_label:   null,
  tenant_id:     TENANT_ID,
  store_id:      STORE_ID,
  action:        "context.switch.tenant",
  target_type:   "tenant",
  target_id:     TARGET_ID,
  request_id:    REQUEST_ID_OK,
  metadata:      { reason: "user request" },
};

// ---------------------------------------------------------------------------
// Spy factory
// ---------------------------------------------------------------------------

function buildSpyDb(): AuditDbLike & {
  insertAuditEvent: jest.MockedFunction<AuditDbLike["insertAuditEvent"]>;
  capturedRows: AuditEventInsertRow[];
} {
  const capturedRows: AuditEventInsertRow[] = [];
  const insertAuditEvent = jest.fn(async (row: AuditEventInsertRow) => {
    capturedRows.push(row);
  });
  return { insertAuditEvent, capturedRows };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("AuditFanoutProcessor", () => {
  let db: ReturnType<typeof buildSpyDb>;
  let processor: AuditFanoutProcessor;

  beforeEach(() => {
    db = buildSpyDb();
    processor = new AuditFanoutProcessor(db);
    // T596: reset metric spies so per-test call-count assertions are clean.
    (recordWorkerJobDuration as jest.Mock).mockClear();
    (recordWorkerProcessingFailure as jest.Mock).mockClear();
  });

  // ── Happy path ─────────────────────────────────────────────────────────

  it("calls insertAuditEvent once on a valid payload", async () => {
    await processor.process(AUDIT_FANOUT_JOB_NAME, VALID_PAYLOAD);
    expect(db.insertAuditEvent).toHaveBeenCalledTimes(1);
  });

  it("maps action, actor_user_id, tenant_id, store_id correctly", async () => {
    await processor.process(AUDIT_FANOUT_JOB_NAME, VALID_PAYLOAD);
    const row = db.capturedRows[0]!;
    expect(row.action).toBe("context.switch.tenant");
    expect(row.actor_user_id).toBe(ACTOR_USER_ID);
    expect(row.tenant_id).toBe(TENANT_ID);
    expect(row.store_id).toBe(STORE_ID);
  });

  it("maps target_type and target_id correctly", async () => {
    await processor.process(AUDIT_FANOUT_JOB_NAME, VALID_PAYLOAD);
    const row = db.capturedRows[0]!;
    expect(row.target_type).toBe("tenant");
    expect(row.target_id).toBe(TARGET_ID);
  });

  // ── id generation ──────────────────────────────────────────────────────

  it("stamps id as a UUID — not sourced from the raw payload", async () => {
    const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
    await processor.process(AUDIT_FANOUT_JOB_NAME, VALID_PAYLOAD);
    const row = db.capturedRows[0]!;
    expect(row.id).toMatch(UUID_RE);
    expect(VALID_PAYLOAD).not.toHaveProperty("id");
  });

  it("generates a distinct id for each job invocation", async () => {
    await processor.process(AUDIT_FANOUT_JOB_NAME, VALID_PAYLOAD);
    await processor.process(AUDIT_FANOUT_JOB_NAME, VALID_PAYLOAD);
    const [r1, r2] = db.capturedRows;
    expect(r1!.id).not.toBe(r2!.id);
  });

  // ── occurred_at absent ──────────────────────────────────────────────────

  it("does not pass occurred_at/occurredAt — DB DEFAULT stamps it", async () => {
    await processor.process(AUDIT_FANOUT_JOB_NAME, VALID_PAYLOAD);
    const row = db.capturedRows[0]! as Record<string, unknown>;
    expect(row).not.toHaveProperty("occurred_at");
    expect(row).not.toHaveProperty("occurredAt");
  });

  // ── Malformed payload ───────────────────────────────────────────────────

  it("throws MalformedAuditJobError when action is missing", async () => {
    const bad = { ...VALID_PAYLOAD, action: undefined };
    await expect(
      processor.process(AUDIT_FANOUT_JOB_NAME, bad),
    ).rejects.toBeInstanceOf(MalformedAuditJobError);
  });

  it("throws MalformedAuditJobError when payload is not an object", async () => {
    await expect(
      processor.process(AUDIT_FANOUT_JOB_NAME, "not-an-object"),
    ).rejects.toBeInstanceOf(MalformedAuditJobError);
  });

  it("does not call insertAuditEvent on a malformed payload", async () => {
    await expect(
      processor.process(AUDIT_FANOUT_JOB_NAME, {}),
    ).rejects.toThrow();
    expect(db.insertAuditEvent).not.toHaveBeenCalled();
  });

  // ── Transient DB error propagation ─────────────────────────────────────

  it("propagates a transient DB error unwrapped so BullMQ can retry", async () => {
    const dbError = new Error("pg: connection refused");
    db.insertAuditEvent.mockRejectedValueOnce(dbError);
    await expect(
      processor.process(AUDIT_FANOUT_JOB_NAME, VALID_PAYLOAD),
    ).rejects.toBe(dbError);
  });

  // ── Metadata — safe ────────────────────────────────────────────────────

  it("stores safe metadata plain object as-is", async () => {
    const payload = { ...VALID_PAYLOAD, metadata: { reason: "test", count: 3 } };
    await processor.process(AUDIT_FANOUT_JOB_NAME, payload);
    expect(db.capturedRows[0]!.metadata).toEqual({ reason: "test", count: 3 });
  });

  // ── Metadata — top-level blocked key ───────────────────────────────────

  it("stores {} when metadata contains top-level 'token' key", async () => {
    const payload = { ...VALID_PAYLOAD, metadata: { token: "abc123" } };
    await processor.process(AUDIT_FANOUT_JOB_NAME, payload);
    expect(db.capturedRows[0]!.metadata).toEqual({});
  });

  it("stores {} for each blocked key at top level", async () => {
    const blocked = ["password", "access_token", "refresh_token", "authorization", "cookie", "secret"];
    for (const key of blocked) {
      db = buildSpyDb();
      processor = new AuditFanoutProcessor(db);
      const payload = { ...VALID_PAYLOAD, metadata: { [key]: "x", safe: 1 } };
      await processor.process(AUDIT_FANOUT_JOB_NAME, payload);
      expect(db.capturedRows[0]!.metadata).toEqual({});
    }
  });

  // ── Metadata — nested blocked key ──────────────────────────────────────

  it("stores {} when a blocked key appears nested inside metadata", async () => {
    const payload = {
      ...VALID_PAYLOAD,
      metadata: { data: { inner: { secret: "shh" } } },
    };
    await processor.process(AUDIT_FANOUT_JOB_NAME, payload);
    expect(db.capturedRows[0]!.metadata).toEqual({});
  });

  it("stores {} when a blocked key is mixed-case (case-insensitive check)", async () => {
    const payload = { ...VALID_PAYLOAD, metadata: { Token: "leak" } };
    await processor.process(AUDIT_FANOUT_JOB_NAME, payload);
    expect(db.capturedRows[0]!.metadata).toEqual({});
  });

  // ── Metadata — null / non-object ───────────────────────────────────────

  it("stores {} when metadata is null", async () => {
    const payload = { ...VALID_PAYLOAD, metadata: null };
    await processor.process(AUDIT_FANOUT_JOB_NAME, payload);
    expect(db.capturedRows[0]!.metadata).toEqual({});
  });

  it("stores {} when metadata is a string", async () => {
    const payload = { ...VALID_PAYLOAD, metadata: "raw string" };
    await processor.process(AUDIT_FANOUT_JOB_NAME, payload);
    expect(db.capturedRows[0]!.metadata).toEqual({});
  });

  it("stores {} when metadata is an array", async () => {
    const payload = { ...VALID_PAYLOAD, metadata: ["a", "b"] };
    await processor.process(AUDIT_FANOUT_JOB_NAME, payload);
    expect(db.capturedRows[0]!.metadata).toEqual({});
  });

  it("stores {} when a blocked key appears inside a nested array element", async () => {
    const payload = {
      ...VALID_PAYLOAD,
      metadata: { items: [{ label: "ok" }, { token: "leak" }] },
    };
    await processor.process(AUDIT_FANOUT_JOB_NAME, payload);
    expect(db.capturedRows[0]!.metadata).toEqual({});
  });

  it("stores {} when metadata is a non-plain object (e.g. Date instance)", async () => {
    const payload = { ...VALID_PAYLOAD, metadata: new Date() };
    await processor.process(AUDIT_FANOUT_JOB_NAME, payload);
    expect(db.capturedRows[0]!.metadata).toEqual({});
  });

  it("stores {} when a nested value is a non-plain object (e.g. { when: new Date() })", async () => {
    const payload = { ...VALID_PAYLOAD, metadata: { when: new Date(), safe: 1 } };
    await processor.process(AUDIT_FANOUT_JOB_NAME, payload);
    expect(db.capturedRows[0]!.metadata).toEqual({});
  });

  it("stores {} when metadata is deeply nested beyond the depth cap", async () => {
    // Build a plain-object chain 12 levels deep — exceeds the cap of 10.
    // The scan must fail closed and return {} rather than passing through.
    let deep: Record<string, unknown> = { safe: true };
    for (let i = 0; i < 12; i++) {
      deep = { nested: deep };
    }
    const payload = { ...VALID_PAYLOAD, metadata: deep };
    await processor.process(AUDIT_FANOUT_JOB_NAME, payload);
    expect(db.capturedRows[0]!.metadata).toEqual({});
  });

  // ── request_id coercion ─────────────────────────────────────────────────

  it("forwards a valid UUID request_id unchanged", async () => {
    await processor.process(AUDIT_FANOUT_JOB_NAME, VALID_PAYLOAD);
    expect(db.capturedRows[0]!.request_id).toBe(REQUEST_ID_OK);
  });

  it("coerces a non-UUID request_id string to null", async () => {
    const payload = { ...VALID_PAYLOAD, request_id: "req-test-001" };
    await processor.process(AUDIT_FANOUT_JOB_NAME, payload);
    expect(db.capturedRows[0]!.request_id).toBeNull();
  });

  it("keeps request_id null when payload carries null", async () => {
    const payload = { ...VALID_PAYLOAD, request_id: null };
    await processor.process(AUDIT_FANOUT_JOB_NAME, payload);
    expect(db.capturedRows[0]!.request_id).toBeNull();
  });

  // ── tenant_id ──────────────────────────────────────────────────────────

  it("forwards a UUID tenant_id to the insert row", async () => {
    await processor.process(AUDIT_FANOUT_JOB_NAME, VALID_PAYLOAD);
    expect(db.capturedRows[0]!.tenant_id).toBe(TENANT_ID);
  });

  it("forwards tenant_id null to the insert row (RLS guards at DB layer)", async () => {
    const payload = { ...VALID_PAYLOAD, tenant_id: null };
    await processor.process(AUDIT_FANOUT_JOB_NAME, payload);
    expect(db.capturedRows[0]!.tenant_id).toBeNull();
  });

  // ── Unknown job name ────────────────────────────────────────────────────

  it("throws UnknownAuditJobError for an unrecognised job name", async () => {
    await expect(
      processor.process("audit.unknown", VALID_PAYLOAD),
    ).rejects.toBeInstanceOf(UnknownAuditJobError);
  });

  it("does not call insertAuditEvent on an unknown job name", async () => {
    await expect(
      processor.process("audit.unknown", VALID_PAYLOAD),
    ).rejects.toThrow();
    expect(db.insertAuditEvent).not.toHaveBeenCalled();
  });

  // ── Job name pin ───────────────────────────────────────────────────────

  it("AUDIT_FANOUT_JOB_NAME is exactly 'audit-fanout'", () => {
    expect(AUDIT_FANOUT_JOB_NAME).toBe("audit-fanout");
  });
});

describe("T303 — OTel traceContext wiring in AuditFanoutProcessor", () => {
  let db: ReturnType<typeof buildSpyDb>;
  let processor: AuditFanoutProcessor;
  let tracerHandle: TestTracerHandle;

  beforeEach(() => {
    tracerHandle = createTestTracerProvider();
    db = buildSpyDb();
    processor = new AuditFanoutProcessor(db);
  });

  afterEach(async () => {
    await tracerHandle.teardown();
  });

  it("processes a job that includes traceContext without error and inserts the row", async () => {
    await processor.process(AUDIT_FANOUT_JOB_NAME, {
      ...VALID_PAYLOAD,
      traceContext: { traceparent: "00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01" },
    });
    expect(db.insertAuditEvent).toHaveBeenCalledTimes(1);
    expect(db.capturedRows[0]!.action).toBe(VALID_PAYLOAD.action);
  });

  it("legacy job without traceContext still inserts normally", async () => {
    await processor.process(AUDIT_FANOUT_JOB_NAME, VALID_PAYLOAD);
    expect(db.insertAuditEvent).toHaveBeenCalledTimes(1);
  });

  it("active context inside process() carries the producer traceId from traceContext", async () => {
    const tracer = trace.getTracer("test-producer");
    const producerSpan = tracer.startSpan("api.audit-enqueue");
    const producerCtx = trace.setSpan(context.active(), producerSpan);
    const traceContext = context.with(producerCtx, () => injectTraceContext());
    producerSpan.end();
    const producerTraceId = producerSpan.spanContext().traceId;

    let contextTraceId: string | undefined;
    const origInsert = db.insertAuditEvent.bind(db);
    db.insertAuditEvent = jest.fn(async (row: AuditEventInsertRow) => {
      const spanCtx = trace.getSpanContext(context.active());
      contextTraceId = spanCtx?.traceId;
      return origInsert(row);
    });

    await processor.process(AUDIT_FANOUT_JOB_NAME, {
      ...VALID_PAYLOAD,
      traceContext,
    });

    expect(contextTraceId).toBe(producerTraceId);
  });
});

describe("T596 — AuditFanoutProcessor metric emission (worker_job_duration, worker_processing_failure)", () => {
  let db: ReturnType<typeof buildSpyDb>;
  let processor: AuditFanoutProcessor;

  beforeEach(() => {
    db = buildSpyDb();
    processor = new AuditFanoutProcessor(db);
    (recordWorkerJobDuration as jest.Mock).mockClear();
    (recordWorkerProcessingFailure as jest.Mock).mockClear();
  });

  it("success: records worker_job_duration_seconds with job_name='audit-fanout' and non-negative duration", async () => {
    await processor.process(AUDIT_FANOUT_JOB_NAME, VALID_PAYLOAD);
    expect(recordWorkerJobDuration).toHaveBeenCalledTimes(1);
    const [attrs, durationSeconds] = (recordWorkerJobDuration as jest.Mock).mock.calls[0]!;
    expect(attrs).toEqual({ job_name: "audit-fanout" });
    expect(typeof durationSeconds).toBe("number");
    expect(durationSeconds).toBeGreaterThanOrEqual(0);
  });

  it("success: does NOT record worker_processing_failure_total", async () => {
    await processor.process(AUDIT_FANOUT_JOB_NAME, VALID_PAYLOAD);
    expect(recordWorkerProcessingFailure).not.toHaveBeenCalled();
  });

  it("malformed payload: records worker_processing_failure with job_name='audit-fanout' and error_class='UnknownError'", async () => {
    // MalformedAuditJobError is not in WORKER_ERROR_CLASSES → "UnknownError".
    const bad = { ...VALID_PAYLOAD, action: undefined };
    await expect(
      processor.process(AUDIT_FANOUT_JOB_NAME, bad),
    ).rejects.toBeInstanceOf(MalformedAuditJobError);

    expect(recordWorkerProcessingFailure).toHaveBeenCalledTimes(1);
    expect(recordWorkerProcessingFailure).toHaveBeenCalledWith({
      job_name: "audit-fanout",
      error_class: "UnknownError",
    });
  });

  it("malformed payload: still records worker_job_duration_seconds (finally branch fires)", async () => {
    await expect(
      processor.process(AUDIT_FANOUT_JOB_NAME, "not-an-object"),
    ).rejects.toBeInstanceOf(MalformedAuditJobError);

    expect(recordWorkerJobDuration).toHaveBeenCalledTimes(1);
    const [attrs] = (recordWorkerJobDuration as jest.Mock).mock.calls[0]!;
    expect(attrs).toEqual({ job_name: "audit-fanout" });
  });

  it("unknown job name: records worker_processing_failure with error_class='UnknownError'", async () => {
    await expect(
      processor.process("audit.unknown", VALID_PAYLOAD),
    ).rejects.toBeInstanceOf(UnknownAuditJobError);

    expect(recordWorkerProcessingFailure).toHaveBeenCalledTimes(1);
    expect(recordWorkerProcessingFailure).toHaveBeenCalledWith({
      job_name: "audit-fanout",
      error_class: "UnknownError",
    });
  });

  it("transient DB error: records worker_processing_failure and rethrows the original error unchanged", async () => {
    const dbError = new Error("pg: connection refused");
    db.insertAuditEvent.mockRejectedValueOnce(dbError);
    await expect(
      processor.process(AUDIT_FANOUT_JOB_NAME, VALID_PAYLOAD),
    ).rejects.toBe(dbError);

    // Generic Error → "UnknownError".
    expect(recordWorkerProcessingFailure).toHaveBeenCalledWith({
      job_name: "audit-fanout",
      error_class: "UnknownError",
    });
    expect(recordWorkerJobDuration).toHaveBeenCalledTimes(1);
  });

  it("multiple invocations: each records exactly one duration call (no leakage between calls)", async () => {
    await processor.process(AUDIT_FANOUT_JOB_NAME, VALID_PAYLOAD);
    await processor.process(AUDIT_FANOUT_JOB_NAME, VALID_PAYLOAD);
    expect(recordWorkerJobDuration).toHaveBeenCalledTimes(2);
    expect(recordWorkerProcessingFailure).not.toHaveBeenCalled();
  });
});
